<? ob_start(); ?>



<!-- main content -->
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="box_stat box_ico">
            <span class="stat_ico stat_ico_1"><i class="li_vallet"></i></span>
            <h4>1 045$</h4>
            <small>Sale (7 days)</small>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="box_stat box_ico">
            <span class="stat_ico stat_ico_2"><i class="li_user"></i></span>
            <h4>865</h4>
            <small>New Users (24h)</small>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="box_stat box_ico">
            <span class="stat_ico stat_ico_3"><i class="li_banknote"></i></span>
            <h4>10 327&euro;</h4>
            <small>Sale (June)</small>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="box_stat box_ico">
            <span class="stat_ico stat_ico_4"><i class="li_truck"></i></span>
            <h4>135</h4>
            <small>Orders (24h)</small>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Locations</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-8">
                        <div id="world_map_vector" style="width:100%;height:300px">
                            <script>
                                countries_data = {
                                    "US": 2320,
                                    "BR": 1945,
                                    "IN": 1779,
                                    "AU": 1486,
                                    "TR": 1024,
                                    "CN": 753
                                };
                            </script>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Country</th>
                                    <th class="col_small col_center">Visits</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><a href="#">United States</a></td>
                                    <td class="col_center">2320</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Brazil</a></td>
                                    <td class="col_center">1945</td>
                                </tr>
                                <tr>
                                    <td><a href="#">India</a></td>
                                    <td class="col_center">1779</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Australia</a></td>
                                    <td class="col_center">1486</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Turkey</a></td>
                                    <td class="col_center">1024</td>
                                </tr>
                                <tr>
                                    <td><a href="#">China</a></td>
                                    <td class="col_center">753</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <div class="box_stat box_pos">
            <img src="/backend/theme/img/blank.png" alt="" class="img_ind">
            <h4>1 045$</h4>
            <small>Sale (7 days)</small>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="box_stat box_neg">
            <img src="/backend/theme/img/blank.png" alt="" class="img_ind">
            <h4>865</h4>
            <small>New Users (24h)</small>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="box_stat peity_chart">
            <div class="peity_wrapper">
                <div class="peity_bar_up">2,5,3,6,8,5</div>
            </div>
            <h4>10 327&euro;</h4>
            <small>Sale (June)</small>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="box_stat peity_chart">
            <div class="peity_wrapper">
                <div class="peity_bar_down">9,6,7,4,6,3</div>
            </div>
            <h4>135</h4>
            <small>Orders (24h)</small>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="box_stat_circular">
            <div class="box_stat_circular_a color_a">
                <h4>865</h4>
                <small>New Users (24h)</small>
            </div>
            <div class="box_stat_circular_middle">
                <div class="easy_chart easy_chart_a" data-percent="42"><i class="glyphicon glyphicon-user"></i></div>
            </div>
            <div class="box_stat_circular_b">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci&hellip;</p>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="box_stat_circular">
            <div class="box_stat_circular_a color_b">
                <h4>1 356</h4>
                <small>Orders (24h)</small>
            </div>
            <div class="box_stat_circular_middle">
                <div class="easy_chart easy_chart_b" data-percent="70"><span>+70%</span></div>
            </div>
            <div class="box_stat_circular_b">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci possimus&hellip;</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Overview</h4>
            </div>
            <div class="chart_wrapper">
                <div class="chart_wrapper">
                    <div id="flot_overview" class="chart_b">
                        <script>
                            data_new_visits = [
                                [new Date('08/02/2012').getTime(),1148],
                                [new Date('08/03/2012').getTime(),920],
                                [new Date('08/04/2012').getTime(),623],
                                [new Date('08/05/2012').getTime(),701],
                                [new Date('08/06/2012').getTime(),502],
                                [new Date('08/07/2012').getTime(),1472],
                                [new Date('08/08/2012').getTime(),1273],
                                [new Date('08/09/2012').getTime(),782],
                                [new Date('08/10/2012').getTime(),410],
                                [new Date('08/11/2012').getTime(),893],
                                [new Date('08/12/2012').getTime(),774],
                                [new Date('08/13/2012').getTime(),621],
                                [new Date('08/14/2012').getTime(),373],
                                [new Date('08/15/2012').getTime(),420]
                            ];
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Latest Images</h4>
            </div>
            <div class="panel-body panel-body-narrow">
                <div class="photo-carousel">
                    <a class="item gal_lightbox" href="gallery/Image01.jpg"><img src="/backend/theme/gallery/ex_width/Image01_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image02.jpg"><img src="/backend/theme/gallery/ex_width/Image02_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image03.jpg"><img src="/backend/theme/gallery/ex_width/Image03_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image04.jpg"><img src="/backend/theme/gallery/ex_width/Image04_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image05.jpg"><img src="/backend/theme/gallery/ex_width/Image05_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image06.jpg"><img src="/backend/theme/gallery/ex_width/Image06_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image07.jpg"><img src="/backend/theme/gallery/ex_width/Image07_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image08.jpg"><img src="/backend/theme/gallery/ex_width/Image08_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image09.jpg"><img src="/backend/theme/gallery/ex_width/Image09_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image10.jpg"><img src="/backend/theme/gallery/ex_width/Image10_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image11.jpg"><img src="/backend/theme/gallery/ex_width/Image11_tn.jpg" alt=""></a>
                    <a class="item gal_lightbox" href="gallery/Image12.jpg"><img src="/backend/theme/gallery/ex_width/Image12_tn.jpg" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="box_user">
            <div class="box_user_main">
                <img class="img-thumbnail pull-left" alt="" src="/backend/theme/img/user_avatar_lg.png">
                <div class="box_user_info">
                    <h2 class="box_user_name">John Smith</h2>
                    <p><span class="icon-map-marker"></span> Wolfchester, Sudan</p>
                    <p><span class="icon-skype"></span> john_smith</p>
                </div>
            </div>
            <ul class="box_user_stats">
                <li><span>34</span> Followers</li>
                <li><span>221</span> Comments</li>
                <li><span>73</span> Videos</li>
            </ul>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Featured Video</h4>
            </div>
            <div class="panel-body panel-body-narrow">
                <div class="fit_vid sepH_a">
                    <iframe src="http://player.vimeo.com/video/53914149?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;color=808080" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
                <a href="http://vimeo.com/53914149" class="text-muted"><small>Cheetahs on the Edge--Director's Cut</small></a>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Social Networks (7 days)</h4>
            </div>
            <div class="panel-body">
                <div class="chart_wrapper">
                    <div id="flot_social" class="chart_b">
                        <script>
                            data_twitter = [
                                [new Date('08/02/2012').getTime(),48],
                                [new Date('08/03/2012').getTime(),63],
                                [new Date('08/04/2012').getTime(),94],
                                [new Date('08/05/2012').getTime(),49],
                                [new Date('08/06/2012').getTime(),82],
                                [new Date('08/07/2012').getTime(),54],
                                [new Date('08/08/2012').getTime(),33]
                            ];
                            data_google = [
                                [new Date('08/02/2012').getTime(),32],
                                [new Date('08/03/2012').getTime(),26],
                                [new Date('08/04/2012').getTime(),51],
                                [new Date('08/05/2012').getTime(),49],
                                [new Date('08/06/2012').getTime(),72],
                                [new Date('08/07/2012').getTime(),40],
                                [new Date('08/08/2012').getTime(),49]
                            ];
                            data_linkedin = [
                                [new Date('08/02/2012').getTime(),22],
                                [new Date('08/03/2012').getTime(),26],
                                [new Date('08/04/2012').getTime(),41],
                                [new Date('08/05/2012').getTime(),38],
                                [new Date('08/06/2012').getTime(),16],
                                [new Date('08/07/2012').getTime(),19],
                                [new Date('08/08/2012').getTime(),47]
                            ];
                            data_facebook = [
                                [new Date('08/02/2012').getTime(),14],
                                [new Date('08/03/2012').getTime(),17],
                                [new Date('08/04/2012').getTime(),9],
                                [new Date('08/05/2012').getTime(),26],
                                [new Date('08/06/2012').getTime(),4],
                                [new Date('08/07/2012').getTime(),31],
                                [new Date('08/08/2012').getTime(),12]
                            ];
                        </script>
                    </div>
                </div>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Social Network</th>
                        <th class="col_small col_center">Visits</th>
                        <th class="col_small col_center">Pageviews</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="#">Twitter</a></td>
                        <td class="col_center">423</td>
                        <td class="col_center">631</td>
                    </tr>
                    <tr>
                        <td><a href="#">Google+</a></td>
                        <td class="col_center">316</td>
                        <td class="col_center">549</td>
                    </tr>
                    <tr>
                        <td><a href="#">LinkedIn</a></td>
                        <td class="col_center">264</td>
                        <td class="col_center">388</td>
                    </tr>
                    <tr>
                        <td><a href="#">Facebook</a></td>
                        <td class="col_center">152</td>
                        <td class="col_center">274</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-sm-5">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Browsers</h4>
            </div>
            <div class="panel-body">
                <div class="chart_wrapper">
                    <div class="chart_b" id="flot_browsers">
                        <script>
                            data_browsers = [
                                { label: "Firefox",  data: 1428},
                                { label: "Chrome",  data: 858},
                                { label: "Safari",  data: 647},
                                { label: "IE",  data: 433},
                                { label: "Opera",  data: 141}
                            ];
                        </script>
                    </div>
                </div>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Browser</th>
                        <th class="col_small col_center">Visits</th>
                        <th class="col_small col_center">% visits</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="#">Firefox</a></td>
                        <td class="col_center">1428</td>
                        <td class="col_center">54%</td>
                    </tr>
                    <tr>
                        <td><a href="#">Chrome</a></td>
                        <td class="col_center">858</td>
                        <td class="col_center">21%</td>
                    </tr>
                    <tr>
                        <td><a href="#">Safari</a></td>
                        <td class="col_center">647</td>
                        <td class="col_center">11%</td>
                    </tr>
                    <tr>
                        <td><a href="#">Internet Explorer</a></td>
                        <td class="col_center">433</td>
                        <td class="col_center">6%</td>
                    </tr>
                    <tr>
                        <td><a href="#">Opera</a></td>
                        <td class="col_center">141</td>
                        <td class="col_center">2%</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Todo List</h4>
            </div>
            <div class="todo-list">
                <h4>Personal</h4>
                <ul class="connectedSortable">
                    <li class="high-pr"><input type="checkbox" class="todo-check"> Buy groceries</li>
                    <li class="low-pr completed"><input type="checkbox" checked class="todo-check"> Do laundry</li>
                    <li class="low-pr"><input type="checkbox" class="todo-check"> Meeting with Macy</li>
                    <li class="high-pr"><input type="checkbox" class="todo-check"> Pick up kids</li>
                </ul>
                <h4>Work</h4>
                <ul class="connectedSortable">
                    <li class="medium-pr"><input type="checkbox" class="todo-check"> Send press releases</li>
                    <li class="low-pr"><input type="checkbox" class="todo-check"> Buy books</li>
                    <li class="high-pr completed"><input type="checkbox" checked class="todo-check"> Update main site</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading"></div>
            <div id="ebro_cal"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel_alt">
            <div class="panel_alt_body">
                <p class="panel_alt_title">
                    <i class="li_mail"></i>
                    <span>Mailbox</span>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In amet obcaecati sequi! Ipsum dolores adipisci inventore placeat&hellip;</p>
                <a href="#" class="btn btn-primary btn-sm">Read More&hellip;</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel_alt">
            <div class="panel_alt_body">
                <p class="panel_alt_title">
                    <i class="li_bulb"></i>
                    <span>Help Center</span>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In amet obcaecati sequi! Ipsum dolores adipisci&hellip;</p>
                <a href="#" class="btn btn-primary btn-sm">Read More&hellip;</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel_alt">
            <div class="panel_alt_body">
                <p class="panel_alt_title">
                    <i class="li_banknote"></i>
                    <span>Invoices</span>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In amet obcaecati sequi! Ipsum dolores adipisci inventore placeat delectus nulla&hellip;</p>
                <a href="#" class="btn btn-primary btn-sm">Read More&hellip;</a>
            </div>
        </div>
    </div>
</div>


<!--[[ page specific plugins ]]-->

<!-- peity (small charts) -->
<script src="/backend/theme/js/lib/peity/jquery.peity.min.js"></script>
<!-- vector map -->
<script src="/backend/theme/js/lib/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/backend/theme/js/lib/jvectormap/maps/jquery-jvectormap-world-mill-en.js"></script>
<!-- easy pie chart -->
<script src="/backend/theme/js/lib/easy-pie-chart/jquery.easy-pie-chart.js"></script>
<!-- charts -->
<script src="/backend/theme/js/lib/flot/jquery.flot.min.js"></script>
<script src="/backend/theme/js/lib/flot/jquery.flot.pie.min.js"></script>
<script src="/backend/theme/js/lib/flot/jquery.flot.time.min.js"></script>
<script src="/backend/theme/js/lib/flot/jquery.flot.tooltip.min.js"></script>
<script src="/backend/theme/js/lib/flot/jquery.flot.resize.js"></script>
<!-- video embed -->
<script src="/backend/theme/js/lib/FitVids/jquery.fitvids.js"></script>
<!-- carousel -->
<script src="/backend/theme/js/lib/owl-carousel/owl.carousel.min.js"></script>
<!-- responsive lightbox -->
<script src="/backend/theme/js/lib/magnific-popup/jquery.magnific-popup.min.js"></script>
<!-- jQueryUi -->
<script src="/backend/theme/js/lib/jquery_ui/jquery-ui-1.10.3.custom.min.js"></script>
<!-- fullcalendar -->
<script src="/backend/theme/js/lib/fullcalendar/fullcalendar.js"></script>

<script src="/backend/theme/js/pages/ebro_dashboard.js"></script>




<?
$html = ob_get_contents();
ob_end_clean();
die(json_encode(array(
            'html' => $html,
            'title' => 'Главная',
            'breadCrumbs' => array(
                array('title' => 'Главная', 'url' => ''),
            ),
        )));
?>