<? ob_start(); ?>



<div class="widget">
    <div class="widget-title">
        <h4><i class="icon-group"></i></h4>
    </div>
    <div class="widget-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th class="hidden-phone">Логин</th>
                    <th>Статус</th>
                </tr>
            </thead>
            <tbody>
                <? foreach ($users as $k => $v) { ?>
                    <tr>
                        <td><?= $k + 1 ?></td>
                        <td><?= $v->firstname ?></td>
                        <td><?= $v->lastname ?></td>
                        <td><?= $v->login ?></td>
                        <td><span class="label label-success">Активен</span></td>
                        <td><a href="#users/edit/<?= $v->id ?>" class="btn mini purple"><i class="icon-edit"></i> Редактировать</a>&nbsp;
                        <span class="btn btn-danger removeUser" data="<?= $v->id ?>"><i class="icon-remove"></i> Удалить</span>
                    </tr>
                <? } ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.removeUser').click(function(event) {
            confirmDialog('Удалить пользователя?', {text : "Удалить", click :function() { alert('Скоро удалим'); }});
        });
    });
</script>

<a href="#users/create" class="btn mini purple">Добавить пользователя</a>



<?
$html = ob_get_contents();
ob_end_clean();
die(json_encode(array(
    'html' => $html,
    'title' => 'Пользователи',
    'breadCrumbs' => array(
        'Пользователи' => '#124',
    ),
)));
?>