<? ob_start(); ?>

<? foreach ($usersGroups as $userGroup) { ?>
    <?/* $this->partial("partials/simpleTable", array(
        'title' => $userGroup['group']->name,
        'controller' => 'users',
        'items' => $userGroup['users'],
        'fields' => array(
            'firstname' => 'Имя',
            'lastname' => 'Фамилия',
        ),
        'deleteOneConfirmationMessage' => 'user',
    )) */?>



    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <?= $userGroup['group']->name ?>
                        <button class="deleteItem tableHeadButton btn btn-danger btn-sm"
                                data-itemId='<?= $userGroup['group']->id ?>' data-deleteConfirmationMessage='group' data-controller='usersgroups'
                                ><i class="glyphicon glyphicon-trash"></i><span>Удалить группу</span></button>
                        <a href="#usersgroups/edit/<?= $userGroup['group']->id ?>" class="tableHeadButton btn btn-info btn-sm"><span class="glyphicon glyphicon-pencil"></span>Редактировать группу</a>
                        <a href="#users/create/<?= $userGroup['group']->id ?>" class="tableHeadButton btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i>Добавить пользователя</a>
                    </h4>
                </div>
                <table id="dt_basic" class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Логин</th>
                            <th>Статус</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <? foreach ($userGroup['users'] as $k => $v) { ?>
                            <tr>
                                <td><?= $k + 1 ?></td>
                                <td><?= $v->firstname ?></td>
                                <td><?= $v->lastname ?></td>
                                <td><?= $v->login ?></td>
                                <td><span class="label label-<?= $v->active ? 'success' : 'danger' ?>"><?= $v->active ? 'Активен' : 'Блокирован' ?></span></td>
                                <td>
                                    <?= $this->tag->editButtonInTable('users', $v->id)  ?>
                                    <?= $this->tag->deleteButtonInTable('users', $v->id, 'user')  ?>
                                </td>
                            </tr>
                        <? } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<? } ?>


<?= $this->tag->addButton("#users-groups/create", 'Добавить группу пользователей')  ?>



<?
$html = ob_get_contents();
ob_end_clean();
die(json_encode(array(
    'html' => $html,
    'title' => 'Пользователи',
    'breadCrumbs' => array(
        array('title'=> 'Пользователи', 'url' => ''),
    ),
)));
?>