<? ob_start(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title"><?= $create ? 'Добавление категории' : 'Редактирование категории' ?></h4>
    </div>
    <div class="panel-body">
        <?= $form->start() ?>
        <?= $form->render('name_ru', 'Название RU') ?>
        <?= $form->render('name_ua', 'Название UA') ?>
        <?= $form->showSubmitButton() ?>
        <?= $form->end() ?>
    </div>
</div>

<? if ($edit && $category->level == 0)
        $this->partial("categories/details") ?>

<? if ($edit && $showSubcategoriesBlock)
    $this->partial("categories/subcategoriesList") ?>


<?
$breadCrumbs[] = array('title'=> 'Категории товаров', 'url' => '#categories');
if ($parentCategory)
   $breadCrumbs = array_merge($breadCrumbs, Admin\Backend\Models\Categories::getParentCategoriesBreadCrumbs($category->id));
if ($edit)
    $breadCrumbs[] = array('title'=> $category->name_ru, 'url' => '');
else $breadCrumbs[] = array('title'=> 'Добавление категории', 'url' => '');

$html = ob_get_contents();
ob_end_clean();
die(json_encode(array(
    'html' => $html,
    'title' => $create ? 'Добавление категории' : 'Редактирование категории',
    'breadCrumbs' => $breadCrumbs,
)));
?>