<? ob_start(); ?>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Категории товаров
                </h4>
            </div>
            <table id="dt_basic" class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Название RU</th>
                        <th>Название UA</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <? foreach ($categories as $k => $v) { ?>
                            <tr>
                                <td><?= $k + 1 ?></td>
                                <td><?= $v->name_ru ?></td>
                                <td><?= $v->name_ua ?></td>
                                <td>
                                    <a href="#categories/edit/<?= $v->id ?>"><i class="icon-pencil"></i> Редактировать</a>&nbsp;
                                    <span class="deleteCategory spanLikeLink" data-categoryId="<?= $v->id ?>"><i class="icon-remove"></i> Удалить</span>
                                </td>
                            </tr>
                        <? } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<a href="#categories/create/0" class="btn btn-success buttonWithMarginTop"><i class="glyphicon glyphicon-plus"></i>Добавить категорию</a>

<? if (sizeof($categories)) { ?>
    <script type="text/javascript">
        var setting = {};
        var zNodes = <?= $treeData ?>;
        $(document).ready(function(){
            treeObj = $.fn.zTree.init($("#treeDemo"), setting, zNodes);
        });
    </script>
    <br><br>
    <ul id="treeDemo" class="ztree"></ul>
<? } ?>

<script type="text/javascript">
    $(document).ready(function() {
        $('.deleteCategory').click(function(event) {
            var userId = $(this).attr('data-categoryId');
            confirmDialog('Удалить категорию?', {text : "Удалить", click :function() {
                    deleteAction('categories', [userId])
            }});
        });
    });
</script>





<?
$html = ob_get_contents();
ob_end_clean();
die(json_encode(array(
    'html' => $html,
    'title' => 'Категории товаров',
    'breadCrumbs' => array(
        array('title'=> 'Категории товаров', 'url' => ''),
    )
)));
?>