<?php return array (
  'errors.checkboxMultiple.minlength' => 'Выберите минимум %d вариантов',
  'errors.cpassword.equalTo' => 'Пароль и подтверждающий пароль должны совпадать',
  'errors.cpassword.required' => 'Введите Ваш пароль еще раз',
  'errors.email.required' => 'Введите Ваш E-mail',
  'errors.email.validemail' => 'E-mail введен неправильно',
  'errors.float' => 'Введите число',
  'errors.max' => 'Введите число меньше или равное %d',
  'errors.maxlength' => 'Поле должно содержать не более %d символов',
  'errors.min' => 'Введите число больше или равноеl %d',
  'errors.minlength' => 'Это поле должно содержать не менее %d символов',
  'errors.number' => 'Введите число',
  'errors.password.required' => 'Введите пароль',
  'errors.password.twodigitsandtwoletters' => 'Пароль должен содержать минимум два символа латиницы и две цифры',
  'errors.required' => 'Поле обязательно для заполнения',
  'errors.secretkey' => 'Неверный код',
  'errors.urlshortname' => 'Некорректное короткое название',
  'errors.validshortname' => 'Некорректное название',
);?>