<? ob_start(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title"><?= $create ? 'Создание группы пользователей' : 'Редактирование группы пользователей' ?></h4>
    </div>
    <div class="panel-body">
        <?= $form->start() ?>
        <?= $form->render('name', 'Название группы') ?>
        <?= $form->render('user_editing', 'Редактирование пользователей') ?>
        <?= $form->render('access_editing', 'Управление доступом') ?>
        <?= $form->render('sections_editing', 'Редактирование разделов') ?>
        <?= $form->showSubmitButton() ?>
        <?= $form->end() ?>
    </div>
</div>


<?
$html = ob_get_contents();
ob_end_clean();
die(json_encode(array(
    'html' => $html,
    'title' => $create ? 'Создание группы пользователей' : 'Редактирование группы пользователей',
    'breadCrumbs' => array(
        array('title'=> 'Пользователи', 'url' => '#users'),
        array('title'=> $create ? 'Создание группы пользователей' : 'Редактирование группы пользователей', 'url' => ''),
    ),
)));
?>